version: 0.2
phases:
  build:
    commands:
      - docker login -u AWS -p $(aws ecr get-login-password --region $AWS_REGION) $ECR_ENDPOINT
      - docker build -t builtimage --build-arg NEXT_PUBLIC_VERCEL_ENV=$NEXT_PUBLIC_VERCEL_ENV
        --build-arg NEXT_PUBLIC_VERCEL_URL=$NEXT_PUBLIC_VERCEL_URL --build-arg
        NEXT_PUBLIC_TARTEEL_VS_API_KEY=$NEXT_PUBLIC_TARTEEL_VS_API_KEY .
      - docker tag builtimage:latest $ECR_IMAGE_URL:latest
      - docker push $ECR_IMAGE_URL:latest
