enum SliceName {
  THEME = 'theme',
  READING_PREFERENCES = 'readingPreferences',
  QURAN_READER_STYLES = 'quranReaderStyles',
  TRANSLATIONS = 'translations',
  TAFSIRS = 'tafsirs',
  AUDIO_PLAYER_STATE = 'audioPlayerState',
  DEFAULT_SETTINGS = 'defaultSettings',
  NAVBAR = 'navbar',
  SESSION = 'session',
  COMMAND_BAR = 'commandBar',
  CONTEXT_MENU = 'contextMenu',
  FONT_FACES = 'fontFaces',
  READING_TRACKER = 'readingTracker',
  READING_VIEW_HOVERED_VERSE = 'readingViewHoveredVerse',
  SIDEBAR_NAVIGATION = 'sidebarNavigation',
  SEARCH = 'search',
  LOCALE = 'locale',
  PERSIST_GATE_HYDRATION = 'persistGateHydration',
  REVELATION_ORDER = 'revelationOrder',
  MICROPHONE = 'microphone',
  GUEST_ENROLLMENT = 'guestEnrollment',
  STUDY_MODE = 'studyMode',
  VERSE_ACTION_MODAL = 'verseActionModal',
  PINNED_VERSES = 'pinnedVerses',
}

export default SliceName;
